- api/source/app.d
- api/source/pastemyst/controllers/meta_controller.d
- api/source/pastemyst/controllers/package.d
- client/src/lib/Footer.svelte
- client/src/lib/api/meta.ts
> showing the current version in the footer based on the git tag

- api/source/pastemyst/controllers/meta_controller.d
- api/source/pastemyst/services/mongo_service.d
- api/source/pastemyst/services/paste_service.d
- client/src/lib/Footer.svelte
- client/src/lib/api/meta.ts
> showing the number of active pastes in the footer

- api/dub.json
- api/dub.selections.json
- api/source/app.d
- api/source/pastemyst/controllers/meta_controller.d
- api/source/pastemyst/controllers/paste_controller.d
- api/source/pastemyst/models/paste.d
- api/source/pastemyst/models/pasty_skeleton.d
- api/source/pastemyst/services/auth_service.d
- api/source/pastemyst/services/changelog_service.d
- api/source/pastemyst/services/config_service.d
- api/source/pastemyst/services/package.d
- api/source/pastemyst/utils/base36.d
- api/source/pastemyst/utils/id_utils.d
- client/package-lock.json
- client/package.json
- client/src/lib/Footer.svelte
- client/src/lib/api/meta.ts
- client/src/routes/changelog.svelte
> github releases based changelog

- client/src/lib/Header.svelte
> [client] nav buttons more accessible

- client/src/lib/Footer.svelte
- client/src/routes/index.svelte
- prefetching changelog
Closes #17
> [client] properly setting title on home page

- client/src/lib/TabbedEditor.svelte
> fixed tabs disappearing on chrome

- api/source/pastemyst/controllers/auth_controller.d
- api/source/pastemyst/controllers/user_controller.d
- api/source/pastemyst/serialization/package.d
- api/source/pastemyst/serialization/user_policy.d
> removing oauthProviderIds from API requests

- api/source/pastemyst/constants/package.d
- api/source/pastemyst/constants/paste_constants.d
- api/source/pastemyst/constants/user_constants.d
- api/source/pastemyst/controllers/paste_controller.d
- api/source/pastemyst/services/user_service.d
- client/src/lib/Header.svelte
- client/src/lib/Tab.svelte
- client/src/lib/TabbedEditor.svelte
- client/src/routes/[paste].svelte
- client/src/routes/create-account.svelte
- client/src/routes/index.svelte
> limits for paste title, pasty title and username lengths

- api/.gitignore
- client/src/lib/CommandPalette.svelte
- client/src/lib/cmdOptions.ts
- closing with escape
Closes #1
> [client] scrolling palette into view

- client/src/lib/Editor.svelte
- client/src/lib/Tab.svelte
- client/src/lib/TabbedEditor.svelte
> editor tabs improvements

- api/config-example.yml
- api/config/config.go
- api/main.go
> [api] configurable host port

- api/db/query.sql.go
- api/go.mod
- api/go.sum
- api/main.go
- api/query.sql
- api/schema.sql
> [api] deleting expired pastes

- api/handlers/auth_handlers.go
- api/main.go
- client/src/app.scss
- client/src/routes/~[user].svelte
> logging out

- api/main.go
- api/schema.sql
- client/src/routes/create-account.svelte
> [client] refreshing page after account creation

- client/src/lib/CommandPalette.svelte
> [client] fixed cmd palette width

- client/src/lib/CommandPalette.svelte
> [client] fixed the cmd pal search on chrome

- client/src/lib/CommandPalette.svelte
> [client] exact matches are on top of the cmdpal

- client/src/lib/Footer.svelte
> [client] active pastes count on page change

- api/db/query.sql.go
- api/query.sql
- api/schema.sql
> case insensitive usernames

- api/changelog/changelog.go
> [api] getting changelog from v2 and v1

- api/auth/middleware.go
- api/handlers/auth_handlers.go
> [api] fixed valid jwt tokens but deleted user

- client/src/routes/[paste].svelte
> [client] copy link button

- client/src/lib/PastyMeta.svelte
- client/src/routes/[paste].svelte
> [client] button for copying pasty content

- client/src/lib/Tab.svelte
> [client] selecting everything when renaming tabs

- client/src/lib/PastyMeta.svelte
- client/src/routes/[paste]/+page.svelte
- client/src/routes/raw/[paste]/[pasty]/+server.ts
> [client] viewing raw pastes

- client/svelte.config.js
> [client] added csp config

- CONTRIBUTING.md
> added a contributing guide

- api/Controllers/PingController.cs
- api/Program.cs
- api/appsettings.Development.json
> Setup controller logging

- .github/workflows/dotnet.yml
> feat(182): created dotnet gh workflow

- api/Models/Language.cs
- api/Program.cs
- api/Services/LanguageProvider.cs
- api/pastemyst.csproj
> feat(177): fetching languages from github linguist

- api/Controllers/LanguagesController.cs
- api/Exceptions/LanguageNotFoundException.cs
- api/Extensions/StringExtensions.cs
- api/Services/LanguageProvider.cs
> feat(202): getting langs

- api/Program.cs
- api/Services/VersionProvider.cs
- api/pastemyst.csproj
> feat(203): getting the version from git tags

- api/Controllers/MetaController.cs
- api/Models/VersionResponse.cs
> feat(204): api for getting the version

- api/Controllers/MetaController.cs
- api/Models/Release.cs
- api/Program.cs
- api/Services/ChangelogProvider.cs
- api/pastemyst.csproj
> feat(201): fetching the changelog

- api/Controllers/PasteController.cs
- api/Services/AuthService.cs
- api/Services/PasteService.cs
> feat(208): getting pastes

- api/Controllers/MetaController.cs
- api/Models/ActivePastesResponse.cs
- api/Services/PasteService.cs
> feat(206): getting the count of active pastes

- api/Controllers/PasteController.cs
- api/DbContexts/DataContext.cs
- api/Migrations/20230306131248_PastyCascadeDelete.Designer.cs
- api/Migrations/20230306131248_PastyCascadeDelete.cs
- api/Services/PasteService.cs
> feat(210): deleting pastes

- api/Controllers/PasteController.cs
- api/DbContexts/DataContext.cs
- api/Migrations/20230307093150_PasteStars.Designer.cs
- api/Migrations/20230307093150_PasteStars.cs
- api/Models/Paste.cs
- api/Services/PasteService.cs
> feat(211): starring pastes

- api/Controllers/PasteController.cs
- api/Services/PasteService.cs
> feat(228): checking if a paste is starred api

- api/Controllers/MetaController.cs
- api/Controllers/PasteController.cs
- api/Models/LanguageStat.cs
- api/Services/PasteService.cs
> feat(225): getting paste lang stats

- api/Controllers/UserController.cs
- api/Models/Page.cs
- api/Models/PageRequest.cs
- api/Services/AuthService.cs
- api/Services/PasteService.cs
- api/Services/UserProvider.cs
> feat(213): getting user's pastes

- client/src/lib/Editor.svelte
- client/src/lib/TabbedEditor.svelte
> feat: create pastes from dnd files

- client/src/lib/Editor.svelte
- client/src/lib/TabbedEditor.svelte
- client/src/routes/+page.svelte
> fix drag and drop on firefox

- api/Program.cs
> fix: cors allowed origins from config

- client/src/lib/Editor.svelte
> fix: lang list, aliases added space after commas

- client/src/app.scss
- client/src/lib/Checkbox.svelte
- client/src/lib/PasteOptions.svelte
> feat: better accessibility of paste options

- client/src/lib/Editor.svelte
- client/src/routes/+page.svelte
> converting indentation

- client/src/lib/TabbedEditor.svelte
> fix: confirming modified content with in-app links

- client/src/lib/CommandPalette.svelte
> feat: added bg color to cmd palette backdrop

- api/Jobs/ExpirePastesJob.cs
- api/Migrations/20230420085840_AddPasteExpiredActionType.Designer.cs
- api/Migrations/20230420085840_AddPasteExpiredActionType.cs
- api/Models/ActionLogType.cs
- api/Program.cs
- api/Services/PasteService.cs
- api/Services/StatsService.cs
- api/pastemyst.csproj
> feat: deleting expired pastes

- api/Controllers/LanguagesController.cs
- api/Services/LanguageProvider.cs
- client/src/lib/Editor.svelte
- client/src/lib/TabbedEditor.svelte
- client/src/lib/api/lang.ts
- client/src/routes/internal/highlight/+server.ts
> separated popular langs at the top of the lang list

- api/Controllers/UserController.cs
- api/Models/PasteWithLangStats.cs
- api/Services/PasteService.cs
- api/Services/UserProvider.cs
- client/src/lib/PasteList.svelte
- client/src/lib/api/paste.ts
- client/src/routes/~[user]/+page.ts
> feat: sorting paste langs on profile page

- client/src/lib/Editor.svelte
- client/src/lib/TabbedEditor.svelte
> fix(client): new tabs have same indent as previous

- README.md
> docs: added how to generate grammars to readme

- client/src/app.scss
> fix: removed custom scrollbars

- api/Controllers/UserController.cs
- api/Models/Paste.cs
- api/Services/AuthService.cs
- api/Services/UserProvider.cs
- client/src/lib/api/user.ts
- client/src/routes/settings/profile/+page.svelte
> feat: account deletion

- api/Models/User.cs
- client/src/lib/api/user.ts
- client/src/routes/~[user]/+page.svelte
> feat: admin role

- client/src/lib/CommandPalette.svelte
- client/src/lib/Editor.svelte
- client/src/lib/Header.svelte
- client/src/lib/command.ts
- client/src/lib/stores.ts
- client/src/routes/+page.svelte
- client/src/routes/[paste]/+page.svelte
- client/src/routes/settings/profile/+page.svelte
> feat: using the command pallete as confirm dialogs

- api/Services/PasteService.cs
- client/src/routes/[paste]/+page.svelte
> fix: disallow pinning private pastes

- api/Services/UserContext.cs
- api/Services/UserProvider.cs
> fix: viewing other's profiles

- client/src/lib/CommandPalette.svelte
- client/src/lib/Header.svelte
- client/src/lib/utils/userAgent.ts
> feat: on macos use cmd+k to open cmd pal

- client/src/lib/Editor.svelte
> feat: re-render preview on language change

- api/Controllers/SettingsController.cs
- api/Models/SetUsernameRequest.cs
- api/Models/Settings.cs
- api/Models/User.cs
- api/Program.cs
- api/Services/AuthService.cs
- api/Services/SettingsService.cs
- api/Services/UserProvider.cs
- client/src/lib/Editor.svelte
- client/src/lib/api/settings.ts
- client/src/lib/indentation.ts
- client/src/lib/stores.ts
- client/src/routes/+layout.svelte
- client/src/routes/+page.ts
- client/src/routes/settings/+layout.svelte
- client/src/routes/settings/+layout.ts
- client/src/routes/settings/behaviour/+page.svelte
> feat: settings system and indentation settings

- client/src/lib/Editor.svelte
- client/src/lib/TabbedEditor.svelte
> fix: creating new tabs

- api/Services/VersionProvider.cs
- api/pastemyst.csproj
> fix: show the proper current version

- api/Controllers/PasteController.cs
- api/Services/PasteService.cs
- client/src/routes/[paste]/+page.svelte
> feat: downloading pastes as zip

- client/package-lock.json
- client/src/routes/internal/highlight/+server.ts
> fix: using getSingletonHighlighter instead of getHighlighter

- README.md
- api/Dockerfile
- api/Exceptions/LanguageNotFoundException.cs
- api/Models/Settings.cs
- api/Services/LanguageProvider.cs
- api/Services/PasteService.cs
- client/src/lib/Editor.svelte
- client/src/routes/settings/behaviour/+page.svelte
- docker-compose.yml
> feat: audotect languages

- api/Controllers/LanguagesController.cs
- api/Services/LanguageProvider.cs
- api/Services/PasteService.cs
- client/src/lib/Editor.svelte
- client/src/lib/api/lang.ts
> feat: autodetect language on paste

- client/src/lib/TabbedEditor.svelte
> fix: drag and drop

- client/.gitattributes
- client/eslint.config.js
- client/src/app.scss
- client/src/lib/Editor.svelte
- client/src/lib/codemirror-themes/dracula.ts
- client/src/lib/codemirror-themes/myst.ts
- client/src/lib/themes.ts
- client/src/routes/[paste]/+page.ts
- client/src/routes/internal/highlight/+server.ts
- client/static/themes/dracula.json
> feat: theme affects codemirror and shiki

- .github/workflows/dotnet.yml
- api/Services/MongoService.cs
- api/Tests/DatabaseFixture.cs
- api/Tests/ExpiresInUtilsTests.cs
- api/Tests/PasteTests.cs
- api/pastemyst.csproj
> feat: api tests

- api/Services/PasteService.cs
- api/Tests/PasteTests.cs
> feat: paste service tests

- api/Controllers/AuthController.cs
- api/Controllers/ImageController.cs
- api/Controllers/LanguagesController.cs
- api/Controllers/MetaController.cs
- api/Controllers/PasteController.cs
- api/Controllers/SettingsController.cs
- api/Controllers/UserController.cs
- api/Jobs/ExpirePastesJob.cs
- api/Jobs/ExpireSessionSettingsJob.cs
- api/Middleware/UserContextMiddleware.cs
- api/Program.cs
- api/Services/ActionLogger.cs
- api/Services/AuthService.cs
- api/Services/ChangelogProvider.cs
- api/Services/IdProvider.cs
- api/Services/ImageService.cs
- api/Services/LanguageProvider.cs
- api/Services/MongoService.cs
- api/Services/OAuthService.cs
- api/Services/PasteService.cs
- api/Services/SettingsService.cs
- api/Services/StatsService.cs
- api/Services/UserContext.cs
- api/Services/UserProvider.cs
- api/Services/VersionProvider.cs
- api/Tests/DatabaseFixture.cs
- api/Tests/PasteTests.cs
> feat: removed service interfaces

- client/src/routes/[paste]/+page.svelte
> fix: language name contrast

- client/src/lib/PasteListItem.svelte
> feat: showing paste edited at on the profile

- client/.git-scripts/install-hooks.sh
- client/.git-scripts/pre-commit.sh
- client/.git-scripts/run-check.sh
- client/.git-scripts/run-lint.sh
> pre-commit hook

- api/Controllers/AuthController.cs
- api/Controllers/UserController.cs
- api/Extensions/EnumMemberExtensions.cs
- api/Jobs/ExpireAccessTokensJob.cs
- api/Middleware/UserContextMiddleware.cs
- api/Models/ActionLogType.cs
- api/Models/Auth/AccessToken.cs
- api/Models/Auth/AccessTokenResponse.cs
- api/Models/Auth/GenerateAccessTokenRequest.cs
- api/Models/Auth/GenerateAccessTokenResponse.cs
- api/Models/Auth/Scope.cs
- api/Program.cs
- api/Services/AuthService.cs
- api/Services/MongoService.cs
- api/Services/PasteService.cs
- api/Services/SettingsService.cs
- api/Services/UserContext.cs
- api/Services/UserProvider.cs
- api/Tests/PasteTests.cs
- client/src/lib/api/auth.ts
- client/src/routes/settings/+layout.svelte
- client/src/routes/settings/access_tokens/+page.svelte
- client/src/routes/settings/access_tokens/+page.ts
> access tokens

- client/src/lib/PasteOptions.svelte
> fix: paste options not getting selected

- api/PasteMyst.Web/Services/VersionProvider.cs
Fixes the issue introduced by #621
> fix: version provider using wrong path

- api/PasteMyst.Web/Dockerfile
- api/PasteMyst.Web/Models/V2/DecryptedPasteDataV2.cs
- api/PasteMyst.Web/Models/V2/PastyV2.cs
- api/PasteMyst.Web/PasteMyst.Web.csproj
- api/PasteMyst.Web/Services/PasteService.cs
> feat: decrypt v2 pastes

- client/src/lib/TabbedEditor.svelte
- client/src/routes/+page.svelte
> fix: reordering of tabs is no longer only visual

- client/package-lock.json
- client/package.json
- client/src/lib/Toaster.svelte
- client/src/lib/toasts.svelte.ts
- client/src/routes/+layout.svelte
- client/src/routes/[paste]/+page.svelte
> feat: custom toast messages

- client/src/app.scss
- client/src/lib/PasteOptions.svelte
- client/src/lib/Spinner.svelte
- client/src/routes/+page.svelte
> feat: added loader when creating pastes

- client/eslint.config.js
- client/src/app.scss
- client/src/lib/PasteHeader.svelte
- client/src/lib/utils/color.ts
- client/src/routes/+layout.svelte
- client/src/routes/[paste]/embed/+page.server.ts
- client/src/routes/[paste]/embed/+page.svelte
- client/static/scripts/iframeResizer.contentWindow.js
- client/static/scripts/iframeResizer.js
- client/vite.config.js
> embedding pastes

- client/src/lib/Editor.svelte
- client/src/lib/TabData.svelte.ts
- client/src/lib/TabbedEditor.svelte
- client/src/routes/+page.svelte
- client/src/routes/[paste]/edit/+page.svelte
> feat: refactored tabbed editor

- .env.example
- README.md
- api/PasteMyst.Web/Dockerfile
- client/.env.example
- client/src/lib/Header.svelte
- client/src/lib/PasteHeader.svelte
- client/src/lib/TabbedEditor.svelte
- client/src/lib/api/announcement.ts
- client/src/lib/api/auth.ts
- client/src/lib/api/fetch.ts
- client/src/lib/api/lang.ts
- client/src/lib/api/meta.ts
- client/src/lib/api/paste.ts
- client/src/lib/api/settings.ts
- client/src/lib/api/user.ts
- client/src/routes/+layout.svelte
- client/src/routes/[paste]/decrypt/+page.server.ts
- client/src/routes/internal/create-encrypted-paste/+server.ts
- client/src/routes/internal/highlight/+server.ts
- client/src/routes/login/+page.svelte
- client/src/routes/settings/profile/+page.svelte
- client/src/routes/~[user]/+page.svelte
- client/src/routes/~[user]/+page.ts
- compose.yml
Closes #652 
Closes #651 
also fixed network issues
> fix: docker issues

- client/src/routes/users/[user]/+server.ts
> feat: redirect /users/[user] to /~[user]

- api/PasteMyst.Web/Program.cs
- client/src/lib/api/errors.ts
- client/src/lib/api/paste.ts
- client/src/routes/+page.svelte
- client/src/routes/[paste]/edit/+page.svelte
> feat: showing paste create errors as toast

- client/src/lib/Header.svelte
> feat: navigation links

- client/src/lib/PasteHeader.svelte
> feat: copy short link to clipboard use paste.ax

- api/PasteMyst.Web/Services/LanguageProvider.cs
> fix: default to text if autodetect cant find lang

- api/PasteMyst.Web/Controllers/UserController.cs
- api/PasteMyst.Web/Services/UserProvider.cs
- api/PasteMyst.Web/Utils/FileUtils.cs
- client/src/routes/settings/profile/+page.svelte
> feat: downloading user data

- api/PasteMyst.Web.Test.Unit/PasteTests.cs
- api/PasteMyst.Web/Services/PasteService.cs
- client/src/lib/Header.svelte
- client/src/lib/PasteHeader.svelte
> feat: allow admins to delete all public pastes

- api/PasteMyst.Web/Services/UserProvider.cs
- client/src/routes/~[user]/+page.svelte
> feat: allow admin to delete all users

- docs/docs/api-docs.md
- docs/docs/api-docs/_category_.json
- docs/docs/api-docs/announcements.md
- docs/docs/api-docs/auth.md
- docs/docs/api-docs/images.md
- docs/docs/api-docs/languages.md
- docs/docs/api-docs/libraries.md
- docs/docs/api-docs/meta.md
- docs/docs/api-docs/pastes.md
- docs/docs/api-docs/ping.md
- docs/docs/api-docs/settings.md
- docs/docs/api-docs/users.md
- docs/docs/getting-started.md
- docs/docs/v2-docs/_category_.json
- docs/docs/v2-docs/data.md
- docs/docs/v2-docs/paste.md
- docs/docs/v2-docs/time.md
- docs/docs/v2-docs/user.md
- docs/docs/v2-docs/v2-api-docs.md
- docs/docusaurus.config.ts
> feat: api docs

- client/src/routes/settings/access_tokens/+page.ts
- client/src/routes/settings/admin/+page.ts
> fix: forbid settings pages when logged out

- client/src/lib/CommandPalette.svelte
- client/src/lib/Editor.svelte
- client/src/lib/command.ts
- client/src/routes/+layout.svelte
> feat: changing theme through command palette

- client/src/lib/Pasties.svelte
> fix: made the shiki theme reactive

- api/PasteMyst.Web/Models/PasteWithLangStats.cs
- api/PasteMyst.Web/Services/UserProvider.cs
- client/src/lib/PasteListItem.svelte
- client/src/lib/api/paste.ts
> feat: showing a paste is encrypted on the profile
